name: .NET Core

on:
  push:
    branches: 
      - master
      - task/*
      - feature/*

jobs:
  default:
    runs-on: ubuntu-20.04
    env:
      configuration: Release
      test_verbosity: normal
      version: 1.2

    steps:
      - uses: actions/checkout@main

      - name: Setup .NET Core
        uses: actions/setup-dotnet@main
        with:
          dotnet-version: 5.0.x

      - name: Install dependencies
        run: dotnet restore --locked-mode

      - name: Build
        run: dotnet build --configuration ${configuration} --no-restore /p:Version=${version}.${GITHUB_RUN_NUMBER}

      - name: Test
        run: dotnet test --no-restore --verbosity ${test_verbosity}

      - name: Pack
        if: github.ref == 'refs/heads/master'
        run: dotnet pack --configuration ${configuration} --no-restore --no-build --output pack /p:Version=${version}.${GITHUB_RUN_NUMBER}

      - name: Publish NuGet Package
        if: github.ref == 'refs/heads/master'
        run: dotnet nuget push ${GITHUB_WORKSPACE}/pack/*.nupkg -k ${{secrets.NUGET_TOKEN}} -s https://api.nuget.org/v3/index.json