name: .NET Core

on:
  push:
    branches: 
      - master
      - task/*
      - feature/*

jobs:
  default:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@main

      - name: Setup .NET Core
        uses: actions/setup-dotnet@main
        with:
          dotnet-version: 3.1.x

      - name: Install dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore /p:Version=1.1.${GITHUB_RUN_NUMBER}

      - name: Test
        run: dotnet test --no-restore --verbosity normal

      - name: Pack
        if: github.ref == 'refs/heads/master'
        run: dotnet pack --no-restore --no-build --output pack /p:Version=1.1.${GITHUB_RUN_NUMBER}

      - name: Publish NuGet Package
        if: github.ref == 'refs/heads/master'
        run: dotnet nuget push ${GITHUB_WORKSPACE}/pack/*.nupkg -k ${{secrets.NUGET_TOKEN}} -s https://api.nuget.org/v3/index.json